# -*- coding: utf-8 -*-
"""01_Data_Engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZvUXu4wieEwr7GRFAUhKOkh1SRqnKqgk
"""

# ---------------------------------------------------------
# Environment Setup
# ---------------------------------------------------------
# Initializing Spark Session...
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, to_date, trim, upper, when

spark = SparkSession.builder \
    .appName("USAspending_Data_Engineering") \
    .config("spark.driver.memory", "4g") \
    .getOrCreate()

print("Spark Running. Version:", spark.version)

# ---------------------------------------------------------
# Mount Google Drive
# ---------------------------------------------------------
from google.colab import drive
drive.mount('/content/drive')

# ---------------------------------------------------------
# Load the Raw Data
# ---------------------------------------------------------
file_path = [
    '/content/drive/MyDrive/FY2026_All_Contracts_Full_20260506/FY2026_All_Contracts_Full_20260506_1.csv',
    '/content/drive/MyDrive/FY2026_All_Contracts_Full_20260506/FY2026_All_Contracts_Full_20260506_2.csv',
    '/content/drive/MyDrive/FY2026_All_Contracts_Full_20260506/FY2026_All_Contracts_Full_20260506_3.csv'
]

# Loading raw data...
print("Attempting to load and combine data from multiple files...")
try:
    raw_df = spark.read.csv(file_path, header=True, inferSchema=True)
    print(f"Successfully loaded and combined {raw_df.count()} total rows.")
    print("\n--- Raw Data Schema ---")
    raw_df.printSchema()

    print("\n--- First 3 Rows ---")
    raw_df.show(3, truncate=False)
except Exception as e:
    print("Error loading files. Please check the file paths.")
    print(e)

from pyspark.sql import functions as F
# Get all columns from the raw loaded dataframe
raw_columns = raw_df.columns

# Generates profiling expressions for ALL columns
profiling_expressions = []
for col_name in raw_columns:
    profiling_expressions.append(
        (F.count(F.when(F.col(col_name).isNull() | (F.trim(F.col(col_name)) == ""), col_name)) / F.count("*") * 100).alias(f"{col_name}_sparsity")
    )
    profiling_expressions.append(
        F.approx_count_distinct(F.col(col_name)).alias(f"{col_name}_cardinality")
    )

# Run the profile in one pass
raw_profile = raw_df.agg(*profiling_expressions).toPandas().transpose()
raw_profile.columns = ['Value']

raw_profile.to_csv('/content/drive/MyDrive/raw_data_profile_summary.csv')

# ---------------------------------------------------------
# Feature Matrix
# ---------------------------------------------------------
keep_list = [
    # Identifiers
    'award_id_piid', 'recipient_uei', 'recipient_name',

    # Financials
    'federal_action_obligation',
    'total_dollars_obligated',
    'base_and_exercised_options_value',
    'current_total_value_of_award',

    # Dates (We need both to calculate 'Performance Duration')
    'action_date',
    'period_of_performance_start_date',
    'period_of_performance_current_end_date',

    # Categorical
    'naics_code',
    'product_or_service_code',
    'awarding_agency_code',
    'awarding_sub_agency_code',
    'funding_sub_agency_code',
    'type_of_contract_pricing',
    'award_type'
]

# Applying the selection
df_selected = raw_df.select([col(c) for c in keep_list if c in raw_df.columns])

print(f"Original count: {len(raw_df.columns)}")
print(f"Final count: {len(df_selected.columns)}")

# ---------------------------------------------------------
# Data Cleaning & Standardization
# ---------------------------------------------------------

# Cleaning text and formatting dates...
df_cleaned = df_selected \
    .withColumn('recipient_name', upper(trim(col('recipient_name')))) \
    .withColumn('action_date', to_date(col('action_date'), 'yyyy-MM-dd')) \
    .withColumn('period_of_performance_start_date', to_date(col('period_of_performance_start_date'), 'yyyy-MM-dd'))

df_cleaned = df_cleaned.fillna({
    'federal_action_obligation': 0.0,
    'total_dollars_obligated': 0.0,
    'base_and_exercised_options_value': 0.0,
    'current_total_value_of_award': 0.0
})

# Drop rows where critical identifying info (Vendor Name or Contract ID) is entirely missing
df_cleaned = df_cleaned.dropna(subset=['recipient_name', 'award_id_piid'])

df_cleaned.printSchema()

# Shows the first 5 rows to verify the cleaning worked
df_cleaned.show(5, truncate=False)
# Drop any row that doesn't have a vendor name or contract ID
df_cleaned = df_cleaned.dropna(subset=['recipient_name', 'award_id_piid'])

# 3. Export to Parquet
export_path = '/content/drive/MyDrive/cleaned_usaspending_features.parquet'

print(f"Exporting dataset to: {export_path}")
try:
    df_cleaned.write.mode("overwrite").parquet(export_path)
    print("Export Complete!")
except Exception as e:
    print("Error during export:")
    print(e)

"""# New Section"""