# -*- coding: utf-8 -*-
"""Feature_Engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mhUZM4sybQWkI9XhnLWfDrm4YlZUlvtC
"""

# ---------------------------------------------------------
# Setup & Load Clean Data
# ---------------------------------------------------------
# Initialize PySpark session
from pyspark.sql import SparkSession
from pyspark.sql import functions as F

spark = SparkSession.builder \
    .appName("USAspending_Feature_Engineering") \
    .config("spark.sql.legacy.timeParserPolicy", "LEGACY") \
    .getOrCreate()

# 2. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# 3. Load the optimized Parquet file from
file_path = '/content/drive/MyDrive/cleaned_usaspending_features.parquet'
print(f"Loading cleaned data from: {file_path}")

df_clean = spark.read.parquet(file_path)
print(f"Loaded {df_clean.count()} rows and {len(df_clean.columns)} columns.")

# ---------------------------------------------------------
# Financial Variance Engineering
# ---------------------------------------------------------

df_features = df_clean.withColumn(
    'cost_overrun_amount',
    F.col('total_dollars_obligated') - F.col('base_and_exercised_options_value')
)

# To prevent dividing by zero
df_features = df_features.withColumn(
    'cost_overrun_pct',
    F.when(
        F.col('base_and_exercised_options_value') == 0, 0.0  # If baseline is 0, variance is 0%
    ).otherwise(
        F.col('cost_overrun_amount') / F.col('base_and_exercised_options_value')
    )
)

print("Financial features created successfully.")

# ---------------------------------------------------------
# Temporal Duration Engineering
# ---------------------------------------------------------

df_features = df_features.withColumn(
    'contract_duration_days',
    F.datediff(F.col('period_of_performance_current_end_date'), F.col('period_of_performance_start_date'))
)

# Again, we prevent dividing by zero (if a contract started and ended on the exact same day).
df_features = df_features.withColumn(
    'daily_burn_rate',
    F.when(
        (F.col('contract_duration_days') == 0) | (F.col('contract_duration_days').isNull()), 0.0
    ).otherwise(
        F.col('total_dollars_obligated') / F.col('contract_duration_days')
    )
)

print("\n--- Feature Engineering Preview ---")
df_features.select(
    'recipient_name',
    'total_dollars_obligated',
    'cost_overrun_pct',
    'contract_duration_days',
    'daily_burn_rate'
).show(20, truncate=False)

df_features.select([
    F.count(F.when(F.col('contract_duration_days').isNull(), True)).alias('null_durations'),
    F.count("*").alias('total_rows')
]).show()

# ---------------------------------------------------------
# Temporal Duration Engineering (Strict Deletion)
# ---------------------------------------------------------

# 1. Drop rows where either date is completely missing
df_clean_dates = df_features.dropna(subset=[
    'period_of_performance_start_date',
    'period_of_performance_current_end_date'
])

# 2. Calculate the raw duration in days
df_clean_dates = df_clean_dates.withColumn(
    'contract_duration_days',
    F.datediff(F.col('period_of_performance_current_end_date'), F.col('period_of_performance_start_date'))
)

# 3. Filter out bad temporal data
# We drop rows where duration is 0 or negative
df_temporal = df_clean_dates.filter(F.col('contract_duration_days') > 0)

# 4. Calculate Daily Burn Rate safely
df_temporal = df_temporal.withColumn(
    'daily_burn_rate',
    F.col('total_dollars_obligated') / F.col('contract_duration_days')
)

# Preview the clean features and the new row count
print(f"Rows remaining after strict temporal cleaning: {df_temporal.count()}")
print("\n--- Cleaned Feature Engineering Preview ---")
df_temporal.select(
    'total_dollars_obligated',
    'cost_overrun_pct',
    'contract_duration_days',
    'daily_burn_rate'
).show(100, truncate=False)

# ---------------------------------------------------------
# Machine Learning Vectorization & Scaling
# ---------------------------------------------------------
from pyspark.ml.feature import VectorAssembler, StandardScaler

ml_features = [
    'total_dollars_obligated',
    'cost_overrun_pct',
    'contract_duration_days',
    'daily_burn_rate'
]

# VectorAssembler: Combine these columns into a single array column called 'raw_features'
assembler = VectorAssembler(
    inputCols=ml_features,
    outputCol="raw_features",
    handleInvalid="skip"
)

df_assembled = assembler.transform(df_temporal)

# StandardScaler
scaler = StandardScaler(
    inputCol="raw_features",
    outputCol="scaled_features",
    withStd=True,
    withMean=True
)

# Fit the scaler to the data, then transform it
scaler_model = scaler.fit(df_assembled)
df_final_ml = scaler_model.transform(df_assembled)

# Final ML-ready vectors
print("\n--- Final ML-Ready Vectors ---")
df_final_ml.select('recipient_name', 'raw_features', 'scaled_features').show(5, truncate=False)

# ---------------------------------------------------------
# Export Engineered Features for ML
# ---------------------------------------------------------
export_path_ml = '/content/drive/MyDrive/engineered_features_ml.parquet'

print(f"Exporting ML-ready dataset to: {export_path_ml}")
df_temporal.write.mode("overwrite").parquet(export_path_ml)