# -*- coding: utf-8 -*-
"""Machine_learning_and_Data_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RF3odXV_iE8li6rQPO8DuK-U9XzTWern
"""

# ---------------------------------------------------------
# Setup and Load Data
# ---------------------------------------------------------
import pandas as pd
from pyspark.sql import SparkSession
from sklearn.ensemble import IsolationForest

# 1. Initialize Spark
spark = SparkSession.builder.appName("USAspending_ML").getOrCreate()

# 2. Mount Drive
from google.colab import drive
drive.mount('/content/drive')

# 3. Load the engineered features
file_path = '/content/drive/MyDrive/engineered_features_ml.parquet'
print("Loading engineered features from Drive...")
df_temporal = spark.read.parquet(file_path)

# 4. Extract the clean features into local Pandas memory
print("Transferring feature matrix to Pandas...")
pdf = df_temporal.select(
    'award_id_piid',
    'recipient_name',
    'total_dollars_obligated',
    'cost_overrun_pct',
    'contract_duration_days',
    'daily_burn_rate'
).toPandas()

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from keras.models import Model
from keras.layers import Input, Dense

print("--- TRAIN/TEST SPLIT ---")

# Keep only Commercial Contracts (< $50M, < 10 years)
commercial_pdf = pdf[
    (pdf['total_dollars_obligated'] < 50000000) &
    (pdf['contract_duration_days'] < 3650) &
    (pdf['total_dollars_obligated'] > 0)
].copy()

# Define our features
features = ['total_dollars_obligated', 'cost_overrun_pct', 'contract_duration_days', 'daily_burn_rate']
X = commercial_pdf[features].fillna(0)

X_train, X_test = train_test_split(X, test_size=0.20, random_state=42)
print(f"Training on {len(X_train):,} contracts. Testing on {len(X_test):,} unseen contracts.")

# ---------------------------------------------------------
# ISOLATION FOREST (TREE-BASED)
# ---------------------------------------------------------
print("\n--- TRAINING ISOLATION FOREST ---")

iso_forest = IsolationForest(n_estimators=100, contamination=0.005, random_state=42, n_jobs=-1)
iso_forest.fit(X_train)
if_test_preds = iso_forest.predict(X_test)
X_test_results = X_test.copy()
X_test_results['if_anomaly_flag'] = [1 if x == -1 else 0 for x in if_test_preds]

print(f"Isolation Forest found {X_test_results['if_anomaly_flag'].sum():,} anomalies in the Test Set.")

# ---------------------------------------------------------
# AUTOENCODER (DEEP LEARNING)
# ---------------------------------------------------------
print("\n--- TRAINING AUTOENCODER ---")
# Convert Pandas DataFrames directly to NumPy arrays for Keras.
X_train_nn = X_train.values
X_test_nn = X_test.values
input_dim = X_train_nn.shape[1]
input_layer = Input(shape=(input_dim,))
encoded = Dense(8, activation='relu')(input_layer)
bottleneck = Dense(2, activation='relu')(encoded)
decoded = Dense(8, activation='relu')(bottleneck)
output_layer = Dense(input_dim, activation='linear')(decoded)

autoencoder = Model(inputs=input_layer, outputs=output_layer)
autoencoder.compile(optimizer='adam', loss='mse')

# Train ONLY on the 80% Pre-Scaled Data
autoencoder.fit(
    X_train_nn, X_train_nn,
    epochs=15, batch_size=256, shuffle=True, validation_split=0.1, verbose=0
)

# Reconstruct the unseen 20% Test Set
reconstructions_test = autoencoder.predict(X_test_nn)
mse_test = np.mean(np.power(X_test_nn - reconstructions_test, 2), axis=1)

# Flag the top 1% highest reconstruction errors in the Test Set as anomalies
threshold_ae = np.percentile(mse_test, 99)
X_test_results['reconstruction_error'] = mse_test
X_test_results['ae_anomaly_flag'] = [1 if error > threshold_ae else 0 for error in mse_test]

print(f"Autoencoder found {X_test_results['ae_anomaly_flag'].sum():,} anomalies in the Test Set.")

# ---------------------------------------------------------
# ENSEMBLE CONSENSUS & ROC-AUC EVALUATION
# ---------------------------------------------------------
print("\n--- ENSEMBLE CONSENSUS VALIDATION ---")

# Calculate Consensus (Where both models output '1' for anomaly)
consensus_count = len(X_test_results[(X_test_results['if_anomaly_flag'] == 1) & (X_test_results['ae_anomaly_flag'] == 1)])
print(f"Consensus: Both models independently flagged {consensus_count:,} identical contracts in the unseen Test Set.")

# Calculating Pseudo-ROC-AUC
# We treated the Isolation Forest flags as the "Ground Truth" to test how well the Autoencoder agrees with it
try:
    roc_auc = roc_auc_score(X_test_results['if_anomaly_flag'], X_test_results['reconstruction_error'])
    print(f"\n>> ENSEMBLE CONSENSUS ROC-AUC SCORE: {roc_auc:.4f} <<")
except Exception as e:
    print("Could not calculate ROC-AUC.")

import pandas as pd

# 1. Filter the test set for consensus anomalies
consensus_indices = X_test_results[
    (X_test_results['if_anomaly_flag'] == 1) &
    (X_test_results['ae_anomaly_flag'] == 1)
].index

# 2. Rescue the text columns (vendor names, agency names) by matching the index
# back to the original commercial_pdf dataframe
consensus_full_data = commercial_pdf.loc[consensus_indices].copy()

# Add the reconstruction error from the results dataframe so we can sort by it
consensus_full_data['reconstruction_error'] = X_test_results.loc[consensus_indices, 'reconstruction_error']

# 3. Sort by the highest Autoencoder Reconstruction Error
top_10_table = consensus_full_data.sort_values(by='reconstruction_error', ascending=False).head(10)

# 4. Defining ideal columns for explanation
ideal_columns = [
    'recipient_name',
    'awarding_agency_name',
    'total_dollars_obligated',
    'cost_overrun_pct',
    'daily_burn_rate',
    'reconstruction_error'
]

existing_columns = [col for col in ideal_columns if col in top_10_table.columns]
top_10_formatted = top_10_table[existing_columns].copy()

# 5. Formating the numbers for reporting purpose
if 'total_dollars_obligated' in top_10_formatted.columns:
    top_10_formatted['total_dollars_obligated'] = top_10_formatted['total_dollars_obligated'].apply(lambda x: f"${x:,.2f}")

if 'cost_overrun_pct' in top_10_formatted.columns:
    top_10_formatted['cost_overrun_pct'] = top_10_formatted['cost_overrun_pct'].apply(lambda x: f"{x:,.2f}%")

if 'daily_burn_rate' in top_10_formatted.columns:
    top_10_formatted['daily_burn_rate'] = top_10_formatted['daily_burn_rate'].apply(lambda x: f"${x:,.2f}/day")

if 'reconstruction_error' in top_10_formatted.columns:
    top_10_formatted['reconstruction_error'] = top_10_formatted['reconstruction_error'].apply(lambda x: f"{x:,.4f}")

print("\n--- TOP 10 CRITICAL AUDIT TARGETS (COMMERCIAL TIER) ---")
display(top_10_formatted)

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

# 1. PREPARE THE DATA FOR PLOTTING
plot_data = X_test_results.copy()
plot_data['Consensus_Risk'] = np.where(
    (plot_data['if_anomaly_flag'] == 1) & (plot_data['ae_anomaly_flag'] == 1),
    'High-Risk Anomaly',
    'Normal Contract'
)

plot_data['recipient_name'] = commercial_pdf.loc[plot_data.index, 'recipient_name']

sns.set_theme(style="whitegrid")
plt.rcParams.update({'figure.dpi': 300, 'axes.titlesize': 14, 'axes.labelsize': 12})

# ==========================================
# PLOT 1: The Risk Distribution (Donut Chart)
# ==========================================
plt.figure(figsize=(8, 8))
risk_counts = plot_data['Consensus_Risk'].value_counts()
colors = ['#2ecc71', '#e74c3c'] # Green for Normal, Red for Risk

plt.pie(risk_counts, labels=risk_counts.index, autopct='%1.2f%%', startangle=140,
        colors=colors, wedgeprops={'edgecolor': 'white', 'linewidth': 2})

centre_circle = plt.Circle((0,0), 0.70, fc='white')
fig = plt.gcf()
fig.gca().add_artist(centre_circle)
plt.title('Total Audit Volume vs. High-Risk Targets', fontweight='bold')
plt.savefig('01_Risk_Distribution.png', bbox_inches='tight')
plt.show()

# ==========================================
# PLOT 2: Financial Exposure (Scatter Plot)
# ==========================================
plt.figure(figsize=(10, 6))
# We use a log scale because government money spans from thousands to billions
sns.scatterplot(
    data=plot_data,
    x='total_dollars_obligated',
    y='daily_burn_rate',
    hue='Consensus_Risk',
    palette={'Normal Contract': '#bdc3c7', 'High-Risk Anomaly': '#c0392b'},
    alpha=0.6,
    s=50,
    edgecolor=None
)

plt.xscale('log')
plt.yscale('log')
plt.title('Financial Exposure: Total Value vs. Daily Burn Rate', fontweight='bold')
plt.xlabel('Total Dollars Obligated (Log Scale)')
plt.ylabel('Daily Burn Rate (Log Scale)')
plt.legend(title='Audit Priority')
plt.savefig('02_Financial_Exposure_Scatter.png', bbox_inches='tight')
plt.show()

# ==========================================
# PLOT 3: Model Separation (Density Plot)
# ==========================================
plt.figure(figsize=(10, 6))
sns.kdeplot(
    data=plot_data,
    x='reconstruction_error',
    hue='Consensus_Risk',
    fill=True,
    common_norm=False,
    palette={'Normal Contract': '#3498db', 'High-Risk Anomaly': '#e74c3c'},
    alpha=0.5
)

plt.xlim(0, np.percentile(plot_data['reconstruction_error'], 99.5))
plt.title('AI Confidence: Mathematical Separation of Anomalies', fontweight='bold')
plt.xlabel('Autoencoder Reconstruction Error (Severity Score)')
plt.ylabel('Density of Contracts')
plt.savefig('03_Model_Separation.png', bbox_inches='tight')
plt.show()

# ==========================================
# PLOT 4: Top 10 Financial Threats (Bar Chart)
# ==========================================
plt.figure(figsize=(12, 6))
# Get the top 10 anomalies by reconstruction error
top_10 = plot_data[plot_data['Consensus_Risk'] == 'High-Risk Anomaly'].sort_values(
    by='reconstruction_error', ascending=False).head(10)

sns.barplot(
    data=top_10,
    x='total_dollars_obligated',
    y='recipient_name',
    color='#e74c3c'
)

plt.title('Top 10 High-Risk Entities by Capital Exposure', fontweight='bold')
plt.xlabel('Total Dollars Obligated ($)')
plt.ylabel('Vendor Name')
plt.gca().xaxis.set_major_formatter(plt.FuncFormatter(lambda x, loc: "{:,}M".format(int(x/1e6))))
plt.savefig('04_Top_10_Threats.png', bbox_inches='tight')
plt.show()